BFTEST=blowfish_test
KDFTEST=pbkdf2_test
CC=gcc
CCFLAGS=-c -std=c99 -Wall -Werror -I../include/
LD=gcc
LDFLAGS=-lbfcrypt-0 -L../src/
RM=rm -rf

all: $(BFTEST) $(KDFTEST)

$(BFTEST): blowfish_test.o
	$(LD) blowfish_test.o -o $(BFTEST) $(LDFLAGS)

$(KDFTEST): pbkdf2_test.o
	$(LD) pbkdf2_test.o -o $(KDFTEST) $(LDFLAGS)

blowfish_test.o: blowfish_test.c
	$(CC) $(CCFLAGS) blowfish_test.c -o blowfish_test.o

pbkdf2_test.o: pbkdf2_test.c
	$(CC) $(CCFLAGS) pbkdf2_test.c -o pbkdf2_test.o

clean:
	$(RM) *o

distclean:
	$(RM) $(BFTEST) $(KDFTEST) *o
