TARGET=libecrypt-0.dll
CC=gcc
CCFLAGS=-c -std=c99 -Wall -Werror -I../include/ecrypt
LD=gcc
LDFLAGS=-lm
RM=rm -rf
OBJS=	blowfish.o \
	pbkdf2.o

all: $(TARGET)

$(TARGET): $(OBJS)
	$(LD) -shared $(OBJS) -o $(TARGET) $(LDFLAGS)

blowfish.o: blowfish.c
	$(CC) $(CCFLAGS) blowfish.c -o blowfish.o

pbkdf2.o: pbkdf2.c
	$(CC) $(CCFLAGS) pbkdf2.c -o pbkdf2.o

clean:
	$(RM) $(OBJS) *o

distclean:
	$(RM) $(OBJS) *o $(TARGET)

