TARGET=libbfcrypt-0.a
CC=gcc
CCFLAGS=-c -std=c99 -Wall -Werror -I../include/bfcrypt
AR=ar rcs
RANLIB=ranlib
RM=rm -rf
OBJS=	blowfish.o \
	pbkdf2.o

all: $(TARGET)

$(TARGET): $(OBJS)
	$(AR) $(TARGET) $(OBJS) 
	$(RANLIB) $(TARGET)

blowfish.o: blowfish.c
	$(CC) $(CCFLAGS) blowfish.c -o blowfish.o

pbkdf2.o: pbkdf2.c
	$(CC) $(CCFLAGS) pbkdf2.c -o pbkdf2.o

clean:
	$(RM) $(OBJS) *o

distclean:
	$(RM) $(OBJS) *o $(TARGET)

